##########################################################
## SERVER
##########################################################

server.port=${PORT:5454}

##########################################################
## DATABASE
##########################################################

spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

##########################################################
## JPA / HIBERNATE
##########################################################

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

##########################################################
## RAZORPAY
##########################################################

razorpay.api.key=${RAZORPAY_API_KEY}
razorpay.api.secret=${RAZORPAY_API_SECRET}

##########################################################
## STRIPE
##########################################################

stripe.api.key=${STRIPE_API_KEY}

##########################################################
## EMAIL
##########################################################

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false

##########################################################
## DEVTOOLS
##########################################################

spring.devtools.livereload.enabled=true

##########################################################
## GEMINI AI
##########################################################

gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=${GEMINI_API_URL}